package main

import (
	"context"
	"database/sql"
	"fmt"
	"log"
	"os"
	"regexp"
	"strings"
	"time"

	_ "github.com/sijms/go-ora/v2"
)

func splitStatements(content string) []string {
	var out []string
	var cur []string
	for _, line := range strings.Split(content, "\n") {
		if strings.TrimSpace(line) == "/" {
			if len(cur) > 0 {
				out = append(out, strings.Join(cur, "\n"))
				cur = nil
			}
			continue
		}
		cur = append(cur, line)
	}
	return out
}

var (
	reQualified = regexp.MustCompile(`\."([A-Z0-9_$#]+)"`)
	rePlain     = regexp.MustCompile(`(?i)CREATE\s+\w+\s+"([A-Z0-9_$#]+)"`)
	reSkip      = regexp.MustCompile(`(?i)SYS_IL|SYS_LOB`)
)

func objName(s string) string {
	if m := reQualified.FindStringSubmatch(s); len(m) > 1 {
		return m[1]
	}
	if m := rePlain.FindStringSubmatch(s); len(m) > 1 {
		return m[1]
	}
	return ""
}

func objType(s string) (string, string) {
	s = strings.TrimSpace(s)
	up := strings.ToUpper(s)
	oname := objName(s)
	switch {
	case strings.HasPrefix(up, "CREATE TABLE"), strings.HasPrefix(up, "CREATE GLOBAL TEMPORARY TABLE"):
		return "TABLE", oname
	case strings.HasPrefix(up, "CREATE SEQUENCE"):
		return "SEQUENCE", oname
	case strings.HasPrefix(up, "CREATE INDEX"), strings.HasPrefix(up, "CREATE UNIQUE INDEX"), strings.HasPrefix(up, "CREATE BITMAP INDEX"):
		return "INDEX", oname
	case strings.Contains(up, "CREATE OR REPLACE"):
		up2 := strings.ToUpper(s)
		switch {
		case strings.Contains(up2, " VIEW "):
			return "VIEW", oname
		case strings.Contains(up2, " FUNCTION "):
			return "FUNCTION", oname
		case strings.Contains(up2, " TYPE "):
			return "TYPE", oname
		case strings.Contains(up2, " PROCEDURE "):
			return "PROCEDURE", oname
		}
	}
	return "", ""
}

func main() {
	if sysDsn := os.Getenv("ORACLE_DSN_SYSTEM"); sysDsn != "" {
		db, err := sql.Open("oracle", sysDsn)
		if err != nil {
			log.Fatal(err)
		}
		ctx, cancel := context.WithTimeout(context.Background(), 120*time.Second)
		defer cancel()
		user := os.Getenv("LOCAL_USER")
		pass := os.Getenv("LOCAL_PASS")
		for _, stmt := range []string{
			fmt.Sprintf("CREATE USER %s IDENTIFIED BY %q DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS", user, pass),
			fmt.Sprintf("GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TRIGGER, CREATE TYPE, CREATE SYNONYM TO %s", user),
			fmt.Sprintf("GRANT UNLIMITED TABLESPACE TO %s", user),
		} {
			if _, err := db.ExecContext(ctx, stmt); err != nil {
				log.Printf("setup stmt error (may be dup): %v", err)
			}
		}
		db.Close()
		fmt.Println("user created/verified:", user)
	}

	db, err := sql.Open("oracle", os.Getenv("ORACLE_DSN"))
	if err != nil {
		log.Fatal(err)
	}
	defer db.SetMaxOpenConns(1)

	data, err := os.ReadFile(os.Getenv("DDL_FILE"))
	if err != nil {
		log.Fatal(err)
	}
	re := regexp.MustCompile(`(?i)\bGENERATED ALWAYS AS IDENTITY\b`)
	content := re.ReplaceAllString(string(data), "GENERATED BY DEFAULT AS IDENTITY")

	raw := splitStatements(content)
	ctx, cancel := context.WithTimeout(context.Background(), 900*time.Second)
	defer cancel()

	clean := func(s string) string {
		s = strings.TrimSpace(s)
		s = strings.TrimSuffix(s, ";")
		var lines []string
		for _, ln := range strings.Split(s, "\n") {
			t := strings.TrimSpace(ln)
			if strings.HasPrefix(t, "--") || t == "" {
				continue
			}
			lines = append(lines, ln)
		}
		return strings.TrimSpace(strings.Join(lines, "\n"))
	}

	exists := func(otype, oname string) bool {
		if otype == "" || oname == "" {
			return false
		}
		var n int
		_ = db.QueryRowContext(ctx,
			"SELECT COUNT(*) FROM user_objects WHERE object_type=:1 AND object_name=:2", otype, oname).Scan(&n)
		return n > 0
	}

	pending := make([]string, 0, len(raw))

	for _, stmt := range raw {
		s := clean(stmt)
		if s == "" {
			continue
		}
		if reSkip.MatchString(s) {
			continue
		}
		otype, oname := objType(s)
		if oname != "" && exists(otype, oname) {
			continue
		}
		pending = append(pending, s)
	}

	var errs = map[string]string{}
	for pass := 0; pass < 8 && len(pending) > 0; pass++ {
		var next []string
		for _, s := range pending {
			if _, err := db.ExecContext(ctx, s); err != nil {
				next = append(next, s)
				errs[s] = err.Error()
			}
		}
		fmt.Printf("pass %d: %d succeeded, %d remaining\n", pass+1, len(pending)-len(next), len(next))
		if len(next) == len(pending) {
			break
		}
		pending = next
	}

	for _, s := range pending {
		name := objName(s)
		fmt.Printf("FAIL %s: %s\n  stmt: %s\n", name, errs[s], s[:min(200, len(s))])
	}

	var n int
	_ = db.QueryRowContext(ctx, "SELECT COUNT(*) FROM user_tables").Scan(&n)
	fmt.Println("tables created:", n)
}
