-- =============================================================================
-- IRF-SERVICE DB UPGRADE (run manually on the real Oracle UAT schema)
-- Connects to:  NETWORK_SETTLEMENT_UAT @ switch-uat...rds.amazonaws.com:1521/ORCL
--
-- Idempotent: each step only runs if it is still missing, so re-running is safe.
-- Run with:  sqlplus user/pass@db @irf-db-upgrade.sql
--            or paste sections into SQL Developer / PL/SQL Developer
-- Verify after:  SELECT table_name FROM user_tables ORDER BY 1;
--                SELECT column_name FROM user_tab_columns
--                  WHERE table_name='IRF_CALLBACK' ORDER BY column_id;
-- =============================================================================
SET SERVEROUTPUT ON

-- -----------------------------------------------------------------------------
-- 1. CREATE TABLE OMAN_NET_IRF  (entity: OmanNetIRFEntity, identity PK)
--    Column sizes below are inferred from the decompiled entity; confirm/adjust
--    sizes to match the source TLF design before running on prod.
-- -----------------------------------------------------------------------------
BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE OMAN_NET_IRF (
            ONI_SER_NUMBER      NUMBER              GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            ONI_LAST_UPDATED    DATE,
            ONI_UPDATED_USER    NUMBER(10),
            ONI_ROUTE           VARCHAR2(50),
            ONI_SUB_ROUTE       VARCHAR2(50),
            ONI_CARD_TYPE       CHAR(1),
            ONI_SEGMENT         VARCHAR2(50),
            ONI_SEGMENT_DESC    VARCHAR2(200),
            ONI_MCC             VARCHAR2(4),
            ONI_MCC_DESC        VARCHAR2(200),
            ONI_IRF_PERCENTAGE  NUMBER(10,4),
            ONI_IRF_FIXED       NUMBER(14,2),
            ONI_IRF_MAX         NUMBER(14,2)
        )';
    DBMS_OUTPUT.PUT_LINE('CREATED: OMAN_NET_IRF');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN
            DBMS_OUTPUT.PUT_LINE('SKIP (already exists): OMAN_NET_IRF');
        ELSE
            RAISE;
        END IF;
END;
/

-- -----------------------------------------------------------------------------
-- 2. CREATE TABLE OMANNET_BIN_DATA  (entity: OmanNetBinDataEntity, identity PK)
-- -----------------------------------------------------------------------------
BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE OMANNET_BIN_DATA (
            OBN_SER_NUMBER      NUMBER              GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            OBN_LAST_UPDATED    DATE,
            OBN_UPDATED_USER    NUMBER(10),
            OBN_PRJ_SER_NUMBER  NUMBER(10),
            OBN_GEN_STATUS      NUMBER(10),
            OBN_ROUTE           VARCHAR2(50),
            OBN_SUBROUTE        VARCHAR2(50),
            OBN_BIN_NUMBER      VARCHAR2(19),
            OBN_CARD_TYPE       CHAR(1),
            OBN_REMARK          VARCHAR2(500)
        )';
    DBMS_OUTPUT.PUT_LINE('CREATED: OMANNET_BIN_DATA');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN
            DBMS_OUTPUT.PUT_LINE('SKIP (already exists): OMANNET_BIN_DATA');
        ELSE
            RAISE;
        END IF;
END;
/

-- -----------------------------------------------------------------------------
-- 3. Add the 13 entity columns missing from the legacy IRF_CALLBACK table
--    (115,314 existing rows; all columns nullable, Oracle default).
--    Sizes match the handover record (§7.2) and IRFCallbackEntity.
-- -----------------------------------------------------------------------------
DECLARE
    v_cnt NUMBER;
BEGIN
    FOR c IN (
        SELECT 'ICB_CARD_CLASSIFICATION' col, 'VARCHAR2(50)'  typ FROM dual UNION ALL
        SELECT 'ICB_CP_MID',             'VARCHAR2(30)'       FROM dual UNION ALL
        SELECT 'ICB_DOM_INTL_FLAG',      'CHAR(1)'            FROM dual UNION ALL
        SELECT 'ICB_FIXED',              'NUMBER'             FROM dual UNION ALL
        SELECT 'ICB_IRF_AMOUNT',         'NUMBER'             FROM dual UNION ALL
        SELECT 'ICB_PERCENTAGE',         'NUMBER'             FROM dual UNION ALL
        SELECT 'ICB_TXN_AMOUNT',         'NUMBER'             FROM dual UNION ALL
        SELECT 'ICB_IS_CREDIT',          'NUMBER(1)'          FROM dual UNION ALL
        SELECT 'ICB_JOB_NUMBER',         'NUMBER'             FROM dual UNION ALL
        SELECT 'ICB_IRD_CODE',           'VARCHAR2(10)'       FROM dual UNION ALL
        SELECT 'ICB_MTI',                'VARCHAR2(4)'        FROM dual UNION ALL
        SELECT 'ICB_RRN',                'VARCHAR2(12)'       FROM dual UNION ALL
        SELECT 'ICB_UNIQUE_ID',          'VARCHAR2(50)'       FROM dual
    ) LOOP
        SELECT COUNT(*) INTO v_cnt FROM user_tab_columns
         WHERE table_name = 'IRF_CALLBACK' AND column_name = c.col;
        IF v_cnt = 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE IRF_CALLBACK ADD (' || c.col || ' ' || c.typ || ')';
            DBMS_OUTPUT.PUT_LINE('ADDED: IRF_CALLBACK.' || c.col || ' ' || c.typ);
        ELSE
            DBMS_OUTPUT.PUT_LINE('SKIP (already exists): IRF_CALLBACK.' || c.col);
        END IF;
    END LOOP;
END;
/

-- -----------------------------------------------------------------------------
-- 4. Sanity check
-- -----------------------------------------------------------------------------
SELECT table_name, column_id, column_name, data_type, data_length, nullable
  FROM user_tab_columns
 WHERE table_name IN ('OMAN_NET_IRF', 'OMANNET_BIN_DATA', 'IRF_CALLBACK')
   AND (table_name IN ('OMAN_NET_IRF', 'OMANNET_BIN_DATA')
        OR column_name IN ('ICB_CARD_CLASSIFICATION','ICB_CP_MID','ICB_DOM_INTL_FLAG',
                           'ICB_FIXED','ICB_IRF_AMOUNT','ICB_PERCENTAGE','ICB_TXN_AMOUNT',
                           'ICB_IS_CREDIT','ICB_JOB_NUMBER','ICB_IRD_CODE','ICB_MTI',
                           'ICB_RRN','ICB_UNIQUE_ID'))
 ORDER BY table_name, column_id;
